linters:
  enable:
    # checks for pass []any as any in variadic func(...any)
    - asasalint
    # checks for dangerous unicode character sequences
    - bidichk
    # checks whether HTTP response body is closed successfully
    #- bodyclose # not supported on Go >=1.18
    # code clone detection
    - dupl
    # checks for unchecked errors
    - errcheck
    # checks for problematic error-wrapping code
    - errorlint
    # checks for pointers to enclosing loop vars.
    - exportloopref
    # computes & checks the cognitive complexity of functions
    - gocognit
    # finds repeated strings that could be replaced by constant
    - goconst
    # does many different things
    - gocritic
    # computes t& checks the cyclomatic complexity of functions
    - gocyclo
    # good ol' gofmt
    - gofmt
    # but see https://github.com/golang/go/issues/20818
    # checks for import formatting
    - goimports
    # checks for security problems
    - gosec
    # checks for things that can be simplified
    - gosimple
    # reports suspicious constructs like misaligned Printf args.
    - govet
    # enforces consistent import aliases.
    - importas
    # detects when assignments to existing vars are unused
    - ineffassign
    # reports long lines
    - lll
    # finds commonly misspelled english words in comments
    - misspell
    # reports ill-formed or insufficient nolint directives
    - nolintlint
    # does many things
    - revive
    # set of rules from staticcheck
    - staticcheck
    # does many things
    - stylecheck
    # detects inappropriate usage of t.Parallel() in tests
    #- tparallel # not support on Go >=1.18
    # parses & type-checks Go code.
    - typecheck
      # remove unnecessary type conversions
    - unconvert
    # reports unused function parameters
    #- unparam # not support on Go >=1.18
    # checks for unused const, vars, funcs and types
    - unused
    # detects leading & trailing whitespace
    - whitespace
linters-settings:
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 1
  revive:
    rules:
      - name: blank-imports
        disabled: true
  staticcheck:
    # SA1019: deprecation warnings. We use a deprecated logger all over the
    # place, for now.
    checks: ["all", "-SA1019"]
output:
  uniq-by-line: false
run:
  timeout: 10m
  skip-files:
    - internal/rest/versions/embed.go
    - internal/hidden/versions/embed.go
    - internal/private/versions/embed.go
    - cmd/load-testing-target-generator/data.go
issues:
  exclude-rules:
    - linters:
        - lll
      source: "^func Test_"
