version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1
  commitlint: conventional-changelog/commitlint@1.0

go_image: &go_image
  resource_class: medium
  docker:
    - image: cimg/go:1.21

node_image: &node_image
  resource_class: small
  docker:
    - image: cimg/node:18.18.0

branch_exclude_main: &branch_exclude_main
  filters:
    branches:
      ignore: [main]

branch_only_main: &branch_only_main
  filters:
    branches:
      only: main

jobs:
  security-scans:
    <<: *go_image
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
          iac-scan: disabled

  lint:
    <<: *go_image
    steps:
      - checkout
      - run:
          name: run lint check
          command: make lint

  unit_test:
    <<: *go_image
    steps:
      - checkout
      - run:
          name: run unit tests with coverage
          command: make coverage
      - store_test_results:
          path: ./coverage/
      - store_artifacts:
          path: ./coverage/

  license_check:
    <<: *go_image
    steps:
      - checkout
      - run:
          name: run license check
          command: PARAM="--validate" make license

  semantic-release:
    <<: *node_image
    steps:
      - checkout
      - run:
          name: Run semantic-release
          command: make release

workflows:
  "Test":
    jobs:
      - lint:
          name: Lint
          <<: *branch_exclude_main
      - security-scans:
          name: Security Scans
          context: analysis_unify
          <<: *branch_exclude_main
      - unit_test:
          name: Unit Tests + Coverage
          <<: *branch_exclude_main
      - prodsec/secrets-scan:
          name: Secrets scan
          context:
            - snyk-bot-slack
          channel: snyk-vuln-alerts-unify
          <<: *branch_exclude_main
      - commitlint/lint:
          name: Commit Lint
          node-version: 20.11.1
          <<: *branch_exclude_main
      - license_check:
          name: License Check
          <<: *branch_exclude_main

  "Release":
    jobs:
      - security-scans:
          name: Security Scans
          context: analysis_unify
          <<: *branch_only_main
      - lint:
          name: Lint
          <<: *branch_only_main
      - unit_test:
          name: Unit Tests + Coverage
          <<: *branch_only_main
